### ISSUE TITLE
Serverfehler beim Aufruf des Backend-Moduls

### ISSUE THREAD

**Issue by Samson1964** [derhaeuptling/contao-mega-menu#1]
Contao 4.4.3 / PHP 7.1

Warning: in_array() expects parameter 2 to be array, null given in /kunden/107305_14053/webseiten/schachbund/website2018/vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php on line 169

Attempted to load class "DataContainer" from namespace "Derhaeuptling\MegaMenu". Did you forget a "use" statement for another namespace?

**Comment by Metis77** [comment]
@qzminski can you have a look please?

**Comment by qzminski** [comment]
Should be fixed in 14dd09d and `1.0.3`.
