### ISSUE TITLE
Contao 4.13.14: missing the Mega Menu item

### ISSUE THREAD

**Issue by wschern** [derhaeuptling/contao-mega-menu#12]
In a fresh Contao 4.13 installation with only derhaeuptling/contao-mega-menu package, with both PHP 7.4 and PHP 8, I have no Mega Menu item under Layout. The corresponding item in the page settings is also missing.

Contao: 4.13.14
Package version: 1.1.0

**Comment by Metis77** [comment]
did you update the database, after installation?

**Comment by wschern** [comment]
Yes, sure!

![image](https://user-images.githubusercontent.com/11224981/205353217-8bf5cde8-a3f5-45ed-8271-811c6f2707c6.png)

**Comment by Metis77** [comment]
Hm, I can not reproduce that issue.
I am sorry.

**Comment by wschern** [comment]
After some trial and error, I can report that the problem only occurs in version 1.1.0. As soon as I downgrade to 1.0.9, everything works as it should.

**Comment by Metis77** [comment]
do you have any error logs from contao.
Between 1.0.9 and 1.1.0 only the frontend templates changed ... so no Idea without error logs.

**Comment by Metis77** [comment]
@wschern Did you find a solution?

**Comment by wschern** [comment]
> @wschern Did you find a solution?

I simply rolled back to version 1.0.9 🤷‍♂️

**Comment by avoca77** [comment]
Ich habe dasselbe Problem mit der Version 1.10.0. Die Erweiterung erscheint nicht im Backend von Contao. Auch wird bei der Installation im Contao-Manager keine Datenbankaktualisierung angeboten, so dass die Vermutung besteht, dass die Erweiterung gar nicht korrekt installiert wird. Wechsle ich wieder auf 1.0.9 dann wird alles korrekt installiert und die Erweiterung ist im Backend verfügbar. Getestet mit Contao 4.13.15 und PHP 8.1
