### ISSUE TITLE
Erweiterung nach Installation nicht im Backend verfügbar

### ISSUE THREAD

**Issue by avoca77** [derhaeuptling/contao-mega-menu#13]
Contao 4.13.15
PHP 8.1
contao-mega-menu 1.10.0
Erweiterung erscheint nach der Installation via Contao-Manager nicht im Backend (kein Menüpunkt). Bei der Installation werden keine Datenbankänderungen angeboten. 
Beim Wechsel auf Version 1.0.9 ist die Erweiterung im Backend verfügbar und funktioniert.
Problem ist schon bekannt: [https://github.com/DERHAEUPTLING/contao-mega-menu/issues/12](url)

**Comment by Metis77** [comment]
Ich kann den Fehler leider nicht reproduzieren.

Könnt ihr mal schauen, ob dies diese Änderung  d64547f  für den Fehler bei euch verantwortlich ist?

**Comment by ThomasfromGermany** [comment]
Ich kann das Verhalten von avoca77 bestätigen und sogar verfeinern.
Jungfräuliche Installation von Contao 4.9 und mit MegaMenu 1.10 ergänzt - kein Datenbankupdate bei der Installation und im Layout-Abschnitt kein MegaMenü-Eintrag.
Gleichfalls mit Contao 4.13.

Version 1.10 entfernt und 1.09 installiert - funktioniert bei Contao 4.9 ordentlich. Unter Contao 4.13 lässt sich die 1.09 nicht installieren.

**Comment by avoca77** [comment]
> Ich kann den Fehler leider nicht reproduzieren.
> 
> Könnt ihr mal schauen, ob dies diese Änderung [d64547f](https://github.com/DERHAEUPTLING/contao-mega-menu/commit/d64547f1f217c1c2296f0adbfc7d0de990be25b3) für den Fehler bei euch verantwortlich ist?

Der Fehler besteht leider immer noch in 4.13.18. Frage: Wie teste ich deine Änderung?

**Comment by Metis77** [comment]
does v1.1.1 fix the issue?

**Comment by avoca77** [comment]
> does v1.1.1 fix the issue?

Ja, das Update hat nun funktioniert. Ich musste die composer.lock löschen, erst dann ging das Update auf 1.1.1. Das lag wahrscheinlich daran, dass ich im Contao Manager die Version 1.0.9 vorgegeben hatte. Eine Änderung auf ^1.0 ging nur nach dem Löschen der composer.lock.
Contao 4.13.19
PHP 8.1
contao-mega-menu 1.1.1
Danke!!
