### ISSUE TITLE
There is no Layout -> Mega menu

### ISSUE THREAD

**Issue by xApep** [derhaeuptling/contao-mega-menu#14]
In Contao 4.13.24 there is no Mega menu under Layout.
Using Version 1.1.1.

![image](https://github.com/DERHAEUPTLING/contao-mega-menu/assets/1315340/581426ae-fa7a-4b9e-9f4a-2a02c726b284)

Even more interesting there are no mega_menu fields in tl_page, well extension dca is not even detected I guess, since no fields are created.

![image](https://github.com/DERHAEUPTLING/contao-mega-menu/assets/1315340/837154dd-7a92-4ff3-b5ad-4514d54402e0)

**Comment by Metis77** [comment]
@xApep version 1.1.2 should solve that issue. 
can you confirm that?

**Comment by xApep** [comment]
I confirm that in 1.1.2 problem is solved. If I do not get back with any other issues, then version 1.1.2 is bug-less :)

Thanks @Metis77

**Comment by Metis77** [comment]
thanks for feedback !
