### ISSUE TITLE
Can't install on Contao 5.3.9

### ISSUE THREAD

**Issue by xApep** [derhaeuptling/contao-mega-menu#16]
I tried to install on:
Contao 5.3.9
Contao Manager: 1.8.5

Here is the dump log

`Problem 1
    - derhaeuptling/contao-mega-menu[1.1.0, ..., 1.1.7] require contao/core-bundle ~4.4 -> found contao/core-bundle[4.4.0, ..., 4.13.44] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires derhaeuptling/contao-mega-menu ^1.1 -> satisfiable by derhaeuptling/contao-mega-menu[1.1.0, ..., 1.1.7].
[99.3MiB/13.49s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[52.6MiB/13.53s] Memory usage: 52.6MB (peak: 220MB), time: 13.53s.
[52.6MiB/13.53s] Finished Composer Cloud resolving.`

**Comment by Metis77** [comment]
This plugin is not yet updated to be used with Contao 5

**Comment by xApep** [comment]
Ouh :S Just from curiosity - why is then available for installation?

**Comment by Metis77** [comment]
>Ouh :S Just from curiosity - why is then available for installation?

Hm not sure, but as far as I understand that error log, at least the error log it says exactly that:

`derhaeuptling/contao-mega-menu[1.1.0, ..., 1.1.7] require contao/core-bundle ~4.4 `

**Comment by Metis77** [comment]
This is related to https://github.com/contao/contao-manager/issues/325
