### ISSUE TITLE
Bei fehlenden Unterseiten wird kein Megamenü-Container erstellt

### ISSUE THREAD

**Issue by Samson1964** [derhaeuptling/contao-mega-menu#2]
Folgende Seitenstruktur als Beispiel:

- Seite 1
-- Unterseite 1
-- Unterseite 2
- Seite 2
- Seite 3

Die Seiten 1, 2 und 3 bekommen ein Megamenü zugeordnet. Aber nur Seite 1 bekommt wirklich ein Megamenü. Absicht oder Fehler?

Wenn es Absicht ist, muß ich A) auf eine andere Erweiterung umsteigen oder B) contao-mega-menu patchen oder C) tote Unterseiten anlegen.

**Comment by Metis77** [comment]
Sinn der Erweiterung ist es, dass man jeder Hauptseite ein beliebiges (in der Regel eben auch auch spezifische) MegaMenu zuweisen kann.
Du kannst aber natürlich auch allen Seiten das gleiche MegaMenu zuweisen.

zB wie hier: https://www.dbb-wolf.de/

**Comment by Samson1964** [comment]
Ich habe 6 Seiten (davon zwei mit Unterseiten) und jeder Seite ein Megamenü mit unterschiedlichen Inhalten zugeordnet. Es werden aber nur die Megamenüs ausgegeben, deren Seiten Unterseiten haben. Bei den 4 Seiten ohne Unterseiten werden keine Megamenüs angezeigt, obwohl Inhalte vorhanden sind.

A) überlege ich noch
B) Patchen hat noch nicht geklappt
C) Tote Unterseite würde klappen. Ich darf die Seite aber nicht "im Menü verstecken".

**Comment by Samson1964** [comment]
Option B scheint auszufallen. Die Entscheidung ob ein Menü erscheint oder nicht, wird wohl dem Core überlassen. Option C bin ich kein Fan, also werde ich die andere Erweiterung nutzen.

**Comment by Metis77** [comment]
Du kannst mir gerne mal per Mail die Contao Zugangsdaten schicken.
Dann schaue ich kurz.
Evtl. ist das wirklich ein Bug.

**Comment by Samson1964** [comment]
Kann ich gern machen. Muß dazu aber wieder die Erweiterung (über Konsole) installieren. Melde mich morgen.

**Comment by qzminski** [comment]
Fixed in 7cb5900. Since this requires template changes you may need to adjust your templates too.

**Comment by qzminski** [comment]
Also in 991bdfa.

**Comment by Samson1964** [comment]
Klasse, danke!
