### ISSUE TITLE
Open on click

### ISSUE THREAD

**Issue by dive13** [derhaeuptling/contao-mega-menu#3]
Is there a way to open the megamenu on click, not on hover?
Same way bootstrap does with the dropdown menues.

**Comment by Metis77** [comment]
A feature like this is not build in, as this plugin is meant to be extended / adjusted to projects needs, anyway.

But you can add it easily with your custom js + css.

**Comment by Metis77** [comment]
PS: drop a line, if you need help adjusting your code.

**Comment by dive13** [comment]
Yes, please ;-) I'm not very familiar with JS

**Comment by Metis77** [comment]
-> mail@derhaeuptling.com

**Comment by jorauch** [comment]
I miss the feauture, too.

**Comment by steinriesen** [comment]
Is it possible to expanded or change the "onclick" template so that the mega menu closes when you click on the menu item again. This has the advantage that you don't have to click outside the mega menu to close it.

**Comment by Metis77** [comment]
feel free to test c8696fe / version 1.1.7

**Comment by steinriesen** [comment]
Thank you very much, a perfect solution!!!

**Comment by steinriesen** [comment]
I'm looking for a solution to open a specific mega menu via a text link in the continuous text, e.g. via JS or is there another solution, e.g. via insert tag like {{open_mega_menu::mm_3}}
I use the on_click Template.

**Comment by Metis77** [comment]
> I'm looking for a solution to open a specific mega menu via a text link in the continuous text, e.g. via JS or is there another solution, e.g. via insert tag like {{open_mega_menu::mm_3}} I use the on_click Template.

The plugin does not offer any insert tags. This might be a good feature for an payed upgrade.
On the other hand, this could also be done with custom JavaScript.

**Comment by steinriesen** [comment]
Hallo,

ich hab das nav_mega_menu_default_noHover_justClick . html5 Template  in der toggle-Version mal angepasst, so das ein Textlink in der Art:
`<a href="#" class="activateLink" data-target="mm_1">Aktiviere mm_1</a> `
mm_1 funktioniert hier auch bis mm_x

dazu führt, das eines der Megamenüs geöffnet wird und die Seite auch direkt nach oben scrollt, wo in aller Regel das Menü ist.
Bitte verwende den Code wie du möchtest! Der Code ist allerdings bei mir aktuell nur im Bereich integriert.

`    <script>
        window.addEventListener("DOMContentLoaded", () => {
            const mm_container = document.querySelectorAll(".mm_container");
            const mm_links = document.querySelectorAll(".mm_link_onClickOnly");

            mm_links.forEach((link) => { 
                link.addEventListener("click", (e) => {
                    e.preventDefault();
                    if (link.classList.contains('mm_isActive')) {
                        link.classList.remove('mm_isActive');
                    } else {
                        mm_links.forEach(link => link.classList.remove('mm_isActive'));
                        link.classList.add('mm_isActive');
                    }
                });
            });

            document.querySelectorAll('.activateLink').forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    const targetClass = this.getAttribute('data-target');
                    const element = document.querySelector(`.mm_container.${targetClass} > .mm_link_onClickOnly`);
                    if (element) {
                        element.classList.add('mm_isActive');
                        alert(`Klasse .mm_isActive wurde zu ${targetClass} hinzugefügt`);
                        window.scrollTo({ top: 0, behavior: 'smooth' });
                    } else {
                        alert('Element nicht gefunden');
                    }
                });
            });

            document.addEventListener("click", (event) => {
                let isClickInside = false;

                mm_container.forEach(container => {
                    if (container.contains(event.target)) {
                        isClickInside = true;
                    }
                });

                if (event.target.classList.contains('activateLink') || event.target.closest('.activateLink')) {
                    isClickInside = true;
                }

                if (!isClickInside) {
                    mm_links.forEach(link => link.classList.remove('mm_isActive'));
                }
            });
        });
    </script>`

**Comment by steinriesen** [comment]
oh da scheint die Codeintegration nicht ganz funktioniert zu haben, die oberen 4 Zeilen gehören auch dazu.
und oben soll es heißen nur im `<head>` Bereich integriert

**Comment by steinriesen** [comment]
nur im <head> Bereich integriert soll es oben heißen
