### ISSUE TITLE
CSS nicht für Individuelle Navigation

### ISSUE THREAD

**Issue by do-while** [derhaeuptling/contao-mega-menu#6]
Das mitgelieferte CSS wirkt nur auf das normale Navigationsmenü, nicht aber auf die Individuelle Navigation.

**Comment by Metis77** [comment]
Hm,

Das modul bräuchte eh mal einiges an Liebe :)
Kommst du derweil zurecht oder brauchst du Hilfe?
Im Frontend kann ich dich gerne unterstützen.

**Comment by do-while** [comment]
Hallo Martin,

danke für Dein Angebot, aber jetzt funktioniert's ja mit der Navigation.
Ist eine schöne Erweiterung, kannte ich bisher nicht.
