### ISSUE TITLE
Contao 4.9 - Section "Mega menu settings" not available in Site Structure -> Edit Page

### ISSUE THREAD

**Issue by ArturJo** [derhaeuptling/contao-mega-menu#7]
> Site Structure -> Edit Page - Go to the page Settings of the page, that will contain the mega menu. In the section "Mega menu settings" check "Enable mega menu".

But there is no "Mega menu settings".
I just installed contao 4.9 . Is there any solution for that?

**Comment by Metis77** [comment]
@qzminski Hi Kamil,
could you look into this?

**Comment by do-while** [comment]
Fixed in version 1.0.8
