### ISSUE TITLE
Contao 4.x - Outside CSS is not loaded

### ISSUE THREAD

**Issue by JensB74** [derhaeuptling/contao-mega-menu#8]
I thougt it was because of the missing 's' on the end of megamenu.css (megamenu.scss):
system/modules/mega_menu/assets/megamenu/megamenu.css
but it isn't.

The file will not be included/loaded ...

Module Version: 1.0.7
Contao Version: 4.9 (but in 4.x also)

By the way, I can confirm the other issue "Section "Mega menu settings" not available in Site Structure -> Edit Page"

**Comment by JensB74** [comment]
will loaded but has no css styles ...

**Comment by Metis77** [comment]
> will loaded but has no css styles ...

Yes.
Beside the HTML the outside template is not prepared.

The idea of the outside template was to accomplish something like this:
https://codyhouse.co/demo/stripe-navigation/index.html
But additional CSS and JS would be needed for this.
