### ISSUE TITLE
Undefined array key "deleteConfirm"

### ISSUE THREAD

**Issue by operatorone** [derhaeuptling/contao-mega-menu#9]
Es gab eine Warnung in Migration Tool von Contao.

`PHP Warning:  Undefined array key "deleteConfirm" in /web/contao_live/vendor/derhaeuptling/contao-mega-menu/dca/tl_mega_menu.php on line 75
`

Kann mit 

`'attributes' => 'onclick="if(!confirm(\''.($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? NULL).'\'))return false;Backend.getScrollOffset()"',`

behoben werden.

Viele Grüße 🙂

**Comment by Metis77** [comment]
Danke für den Hinweis.
Kannst du kurz bestätigen, dass der neue Release Tag 1.0.9 das Problem löst?

**Comment by operatorone** [comment]
Jo, sieht gut aus. Danke 🙂
